### ISSUE TITLE
Cannot find module 'convert-source-map'

### ISSUE THREAD

**Issue by davidreher** [smrq/tsify#28]
Hey there,

I wanted to use tsify in my project. I installed it via npm and added it to my grunt-browserify config.

My first approach for adding it to my browserify config file was

    plugin: ['tsify']

and my second was

    preBundleCB: function (bundle) {
      bundle.plugin('tsify', { target: 'ES5' });
    }

both times the browserify task fails with the following message:

    Cannot find module 'convert-source-map'

BTW: how do I have to create my TS files? Can I use internal modules as described [here](http://www.typescriptlang.org/Handbook#modules) or do I have to use external modules and the `export` keyword as described [here](http://www.typescriptlang.org/Handbook#modules-going-external)

Thanks for the help

**Comment by smrq** [comment]
Are you behind some sort of corporate proxy, or using a private npm registry, or... something?  I can't imagine why you wouldn't be able to resolve `convert-source-map`.  Is it there in `/node_modules/tsify/node_modules/convert-source-map`?

To work with Browserify you would need to use external modules, as in the second link.  I think that is worth adding to the readme.

**Comment by davidreher** [comment]
Hm strange, I did not have the node_modules folder at all ... I removed the tsify folder and ran `npm install` again ... now everything runs fine but tsify isn't compiling the ts files ...
I get 
```
Running "browserify" (browserify) task

Done, without errors.
```

but it doesn't seem to work ... the bundle does not contain the compiled files and I don't get errors when using incorrect syntax

**Comment by smrq** [comment]
I dunno, it's hard to tell based on just that, but it sounds like you have configuration issues, whether in your Gruntfile, your package.json, something about your folder structure perhaps... any or all of the above.  Not sure what to tell you other than take a close look at all the relevant docs.  I suspect someone intimately familiar with `grunt-browserify` might be able to help more.  Regardless, I don't think there's any problem with `tsify` in particular at fault here.  Feel free to open a new issue if you come across some concrete, reproducible problem.
