### ISSUE TITLE
Cannot find name 'module'.

### ISSUE THREAD

**Issue by ddennis** [smrq/tsify#29]
Hi 

Sorry if i have complete misunderstood this plugin, i am expectng to use it with my browserify project.
enabling me to use current browserify syntax, and type annotations.

I'am on Windows, using gulp:

    gulp.task('browserify', function() {
        var bundler = browserify({
            entries: ['./client/src/main'],
            extensions: ['.ts'],
            debug: true
     }).plugin('tsify', { noImplicitAny: true, module: 'commonjs' });
     var bundle = function() {
     bundleLogger.start();
     return bundler
     .bundle()
     .on('error', handleErrors)
     .pipe(source('app.js'))
     .pipe(gulp.dest(buildDir))
     .on('end', bundleLogger.end);
     };
     return bundle();
 });

When i start requiring modules i get the following error:
 TS2304: client/src/main.ts(2,14): TS2304: Cannot find name 'require'.

main.ts
	var config = require('./routes')
routes.ts
	var config = function() {	}
	module.exports = config;

Removing the require statement stops the error
Any help would be much appreciated
/Dennis .

**Comment by smrq** [comment]
The TypeScript module syntax is slightly different, although you otherwise have the right idea.

The correct syntax is:

```
import config = require('./routes');
```

```
var config = function () {};
export = config;
```

I recommend reading the TypeScript docs carefully.

**Comment by ddennis** [comment]
Thank you for the quick response. I was hoping i didn't have to change the whole project.

Based on your response i conclude that there is no way of keeping the original browserify syntax, i have to implement specific typescript syntax and change all files to .ts

Thanks
/Dennis

**Comment by smrq** [comment]
No, you can use any node modules... other than the syntax change for any files that you write using TypeScript, everything is as normal for Browserify.

**Comment by scamden** [comment]
does this mean you cannot use requires inline like this?

```
angular.module('myModule', [
    require('./ItemFieldFace')
]);
```

**Comment by danieldram** [comment]
That's what I am most concerned about too.. I build ng apps this way
