### ISSUE TITLE
Typescript 1.5 support?

### ISSUE THREAD

**Issue by HerringtonDarkholme** [smrq/tsify#37]
It will be a lot help! However,given the breaking API change. TS1.5 and TS1.4- won't play well together without branching code. https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes

Will it be supported?

**Comment by smrq** [comment]
Once TS1.5 is released, I certainly intend to support it.  The API changes mean that it will be more work than just bumping a version number, but otherwise there is no problem.

Closing for now, as TS1.5 is still in alpha.

**Comment by rogerjose81** [comment]
+1 for this requirement, TS 1.5 is now in beta, thus the API should not change.

**Comment by smrq** [comment]
This is supported since 0.9.0!  Just install whatever version of `typescript` you want alongside `tsify`.

**Comment by rogerjose81** [comment]
Thanks. I suggest you to document this on the README.

And one more question, does tsfy supports the "tsconfig.json" file or is there a plan for supporting it?

**Comment by smrq** [comment]
Not yet: #51
