### ISSUE TITLE
Can typescript from npm be used?

### ISSUE THREAD

**Issue by hexaglow** [smrq/tsify#40]
The Typescript version currently in use by this plugin is bundled inside the repo. Is there any particular reason for this? I had a quick skim of tsc.js but I couldn't find any indication that it had been modified (feel free to correct me - maybe if this is the case, you could add a note to the README so other people don't get confused). I'm available to modify the code to facilitate this if you would like.

**Comment by smrq** [comment]
Presently there is a slight modification step as you can find in `unwrapCompiler.js`.  It's not really a long-term solution; at the time of writing, the compiler was not programmatically accessible without alteration, though I think that changed with TS 1.4 (or 1.5 beta?).  I expect that it would be some effort to switch over to using the proper public API, so I haven't gotten around to it yet.

If you want to take a crack at it, be my guest!  I wouldn't say no to a PR.

**Comment by hexaglow** [comment]
I'm on mobile right now so I can't test it out, but a cursory glance suggests that you are just injecting a direct export into the compiler, correct? The functions that are being called in Tsifier.js appear to have exactly the same signature as those in the actual TS api, so it *should* be a very easy replacement. I'll get to work on it tomorrow.

**Comment by smrq** [comment]
Beautiful, I hope that's the case.

**Comment by hexaglow** [comment]
I've patched it to work with raw TS 1.4, but the sourcemap tests are failing - should I be concerned about this, or are the comparison maps just out of date?

**Comment by hexaglow** [comment]
OK - my repo has been updated and is now on TS 1.5 beta and fully test compliant.

**Comment by smrq** [comment]
Thanks!  Merged into v0.9.0, will be pushed to npm as soon as the Travis build gets around to it.
