### ISSUE TITLE
support for sourceRoot

### ISSUE THREAD

**Issue by flyon** [smrq/tsify#46]
I was using this before:   tsc --sourceMap --sourceRoot "../src", which was working for me.

Now I'm using browserify + grunt + tsify with the following in Gruntfile.js:

preBundleCB: function (bundle) {
   bundle.plugin('tsify', { target: 'ES5', module: 'commonjs', sourceMap:true,sourceRoot:'../src2' });
}

but I don't think 'sourceRoot' is doing anything?

**Comment by smrq** [comment]
I think this option was added with TS 1.5?  Anyway, right now compiler options are whitelisted; I'm going to change them to be blacklisted instead.  (Some options, like `module`, are set automatically.)

**Comment by smrq** [comment]
Equivalent to #50
