### ISSUE TITLE
Example for usage with Karma

### ISSUE THREAD

**Issue by cmlenz** [smrq/tsify#48]
This is more of a question than an issue, I hope that's okay.

I'm trying to get Jasmine unit tests working, where both the code under test and the unit tests are written in TypeScript, and the tests are run using Karma (via karma-browserify). But I'm not having much luck getting this to work.

The error I'm getting right now is that Karma can't resolve an imported file, the output is

    Cannot find module '[object Object]' from /some/path/on/my/machine

An example for using `tsify` in this scenario would be much appreciated. Do you happen to know of any that I could take a look at?

I'll update the tsify test repo I made for #43 to show the problems I'm having in a bit.

**Comment by cmlenz** [comment]
Okay I've updated my test repo at https://github.com/cmlenz/tsify-test

I'm running Karma through Gulp with the following task:

    gulp.task('test', function() {
      return gulp.src('src/**/*.spec.ts')
        .pipe(karma({
          frameworks: ['browserify', 'jasmine'],
          preprocessors: {
            'src/**/*.ts': ['browserify'],
          },
          browserify: {
            plugin: ['tsify', {target: 'ES5'}]
          },
          browsers: ['PhantomJS']
        })).on('error', function(error) {
          throw error;
        });
    });

That results in the resolve error mentioned above. Any ideas?

**Comment by smrq** [comment]
Test issues right now, I'll get back to you on this once everything isn't on fire.

**Comment by smrq** [comment]
I've personally never used `gulp-karma`; you could try:

```js
var karma = require('karma').server;

gulp.task('test', function (done) {
  karma.start({
    singleRun: true,
//    ... more config ...
  }, done);
});
```

Seems to work for me.  According to the [Karma docs](https://github.com/karma-runner/gulp-karma) that is the proper way to use Karma from Gulp.

**Comment by bendrucker** [comment]
Don't use a plugin. Use [karma-as-promised](https://www.npmjs.com/package/karma-as-promised) (mine) since Karma's public API doesn't use Node-style callbacks. Instead it calls back with the process exit code and so using @smrq's basic example above won't inform gulp of failed test runs.

**Comment by cmlenz** [comment]
Thanks, I had totally missed that I shouldn't be using the plugin. But I'm still having trouble getting it to work. Can you perhaps post an example of how the Karma config should look to include tsify? Thanks.

**Comment by bendrucker** [comment]
Now that I look back, your karma-browserify config is invalid. In order to define options, the entry in `plugin`/`transform` needs to be an array. You can't just put options after the module name as you have. The error you're getting is exactly what you'd expect if you tried to `require({target: 'ES5'})`

**Comment by cmlenz** [comment]
@bendrucker Oh that was a rather embarrassing error, thanks for pointing it out! I've now fixed the karma config, and it seems to mostly work. See https://github.com/cmlenz/tsify-test/commit/90fffb0a43fba5f0ae8671227e1b1b91d91c1076

However I must admit I couldn't see much of a difference between using karma directly and using karma-as-promised, and using it as you suggested actually results in Gulp not exiting when there are test failures (see https://github.com/cmlenz/tsify-test/commit/d0d9fe3959e65b5399b89af262298eeb1a6bbba5).

**Comment by bendrucker** [comment]
Well you have to use `singleRun: true` or nothing exits

**Comment by cmlenz** [comment]
@bendrucker I have that in the Gulpfile, but even setting it to `true` in the Karma config itself doesn't change the behavior.
