### ISSUE TITLE
Add support for full range of compiler options

### ISSUE THREAD

**Issue by berwyn** [smrq/tsify#50]
It would be really great if we could use the full range of compiler options or specify a tsconfig.json, especially as new features are added and we want to flag them on (emitDecoratorMetadata added in 1.5, for example).

**Comment by smrq** [comment]
All options are now passed through to tsc as of v0.11.0.  The only caveat is that some options may have no effect, particularly if they are options for the `tsc` CLI rather than the compiler itself.
