### ISSUE TITLE
Support tsconfig.json

### ISSUE THREAD

**Issue by smrq** [smrq/tsify#51]

**Comment by rogerjose81** [comment]
Thanks.

In case it helps someone, I'm loading the tsconfig.json configuration in this "manual" way (meanwhile official support comes out?):

const tsConfig = require('./tsconfig.json');

gulp.task('script', function() {
    const self = this;
    var b = browserify(CLIENT_DIR + '/main.ts', {
        debug: true,
        cache: {},
        packageCache: {}
    });
    b = watchify(b);
    b
        .plugin('tsify', tsConfig.compilerOptions)
        .on('update', function() {
            scriptBundleShare.call(self, b);
        });
    return scriptBundleShare.call(this, b);
});

function scriptBundleShare(b) {
    b.bundle()
        .on('error', reportError)
        .pipe(source(SCRIPT_BUNDLE_NAME))
        .pipe(gulp.dest(PUBLIC_DIR + '/js'))
        .pipe(livereload());
    return b;
}

**Comment by smrq** [comment]
Cool, thanks for the snippet.

**Comment by smrq** [comment]
Released in 0.11.1.  Like `tsc`, `tsify` will search the current working directory and up for a `tsconfig.json`.  Any options passed to `tsify` will override those options.

**Comment by battmanz** [comment]
By NOT specifying an entry (or main) file will `tsify` compile all referenced files in the `tsconfig.json` file? That's how `tsc` works, but so far I am unable to make `tsify` do the same.

**Comment by smrq** [comment]
No, Browserify needs to know which file (or files) to use as an entry point.  "Compiling all files" isn't really a sensible task when using Browserify.

**Comment by battmanz** [comment]
Okay, I see the need for an entry file, and I know which file of mine is the entry file. So really, my question is how do I tell `tsify` about the `*.d.ts` files (the ones I installed via `tsd`)?

**Comment by smrq** [comment]
Either a `/// <reference path="path/to/typings.d.ts" />` in your entry file, or just add the `*.d.ts` as another entry

**Comment by felixfbecker** [comment]
@smrq How can I add *.d.ts as another entry? Browserify doesn't seem to accept globs.

**Comment by felixfbecker** [comment]
Ok I got it working with globby but it doesnt seem to find my tsconfig.json. I have basedir set to `src` and my tsconfig.json is located in the directory of the gulpfile.
