### ISSUE TITLE
Version 0.11.1 do not working for me

### ISSUE THREAD

**Issue by tjoskar** [smrq/tsify#52]
Hi,

When I run `browserify ./app/boot.ts -p [ tsify --noImplicitAny ]` with version `0.11.0` all works fine but if I install `0.11.1` I only get an empty browserify file: 

```javascript
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){

},{}]},{},[1])
```

If I downgrade to version `0.11.0` everythings works well again. Do I missing something? 
I'm using version `10.2.1` of browserify.
My `tsconfig.json`:

```JSON
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "noImplicitAny": true,
        "removeComments": true,
        "preserveConstEnums": true,
        "outDir": "./.tmp/"
    },
    "files": [
        "./typings/all.d.ts",
        "./app/boot.ts"
    ]
}
```

**Comment by smrq** [comment]
Hmm, I strongly suspect that `outDir` is the culprit, although I would have to test it to make sure.  Do you need it?  (Browserify will not respect it anyway, since it has its own rules for where to write files.)

**Comment by smrq** [comment]
Confirmed that this was the problem.  Try 0.11.2.
