### ISSUE TITLE
importing github repository

### ISSUE THREAD

**Issue by ddennis** [smrq/tsify#53]
Hi 

My problem it importing a library from github and using it through my package.json, i understand this might be a issue with the libary i am using. But since it works fine when i am not using tsify, i am asking here.

I am using tsd https://github.com/DefinitelyTyped/tsd , which generates a typings file,  :

    /// <reference path="../../typings/tsd.d.ts" />
-
the content of my typings file ../../typings/tsd.d.ts

    ///<reference path="underscore/underscore.d.ts" />
    ///<reference path="pixi/pixi.d.ts" />

-

    import _ = require('underscore'); // works fine

    import pixi = require('pixi.js'); // TS2307: client/src/App.ts(7,23): TS2307: Cannot find external module 'pixi.js'

My package.json

    "dependencies": {
        ....
        "underscore": "^1.8.3",
        "pixi.js": "git://github.com/goodboydigital/pixi.js.git",
        ....
      }

If i disable the .plugin(tsify) in my gulp task, and use normal browserify syntax it works fine:

    var _ = require('underscore');
    var pixi = require('pixi.js');
    console.log (" testApp.js > pixi = " , pixi);

Thanks 
/Dennis

**Comment by ddennis** [comment]
Hi -
My mistake, It seem the library was already on npm, so i could consume it that way.

/Dennis

**Comment by ddennis** [comment]
Hello Again.

I am still having problems, the case is the same as mentions earlier, it works if i disable the .plugin(tsify) in my gulp task, and use normal browserify syntax it works fine:

    var _ = require('underscore');
    var pixi = require('pixi.js');

Any help would be mush appriciated.
/Dennis

**Comment by smrq** [comment]
Hey Dennis,
What that error means is that the TypeScript compiler can't find typings for that module.  Looking at the [type definition on DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped/blob/70737c2a2496f7a13c4da63eb00081cad94d19f1/pixi/pixi.d.ts), it looks like it assumes that there will be a global variable called `PIXI`, rather than an npm-compatible module that you can `require`.  So the problem is a mismatch between the npm module and the relevant type definition.

One way of dealing with this is to declare your own module like this, after including `pixi.d.ts`:
```js
declare module 'pixi.js' {
    export = PIXI;
}
```

**Comment by ddennis** [comment]
Thanks alot - It works like magic. Was banging my head against the wall.

A follow up question, if you have the time?

Is it correct that i need to have a typings file for every node_module i want to use.
And if there is no typings definition, i need to create a basic one like the one you showed me.

    declare module 'whatever' {
        export = whatever;
    }

Thanks again.
/Dennis

**Comment by smrq** [comment]
Yep!  The `declare module 'whatever'` line says that there exists a `require`-able module.  Without it, TypeScript won't know that there even is a node module to pull in, so it will error out.
