### ISSUE TITLE
Errors on first compilation prevent watchify from watching

### ISSUE THREAD

**Issue by LPGhatguy** [smrq/tsify#62]
If a TypeScript file has a syntax error, regardless of it being caught, watchify will not watch the file.

I've created a minimal-ish test case here:
https://github.com/LPGhatguy/gulp-watchify-tsify-bug

This may be related to issue #24

**Comment by smrq** [comment]
Oh, that's interesting.  I can look into this.

**Comment by LPGhatguy** [comment]
Any updates on the issue?

**Comment by smrq** [comment]
This is a slightly obscure pipelining issue.  If there are compilation errors that prevent emitting of the program (and thus continuation of the pipeline) -- which would be either syntax errors, or semantic errors with the optional `noEmitOnError` flag -- then the pipeline never reaches the point of notifying about the additional files, so only the entry point(s) get watched.  So, for instance, with the dependency tree:

```
main.ts
|
+-- sub.ts
    |
    +-- Broken.ts
```

neither Broken.ts nor the working sub.ts will be watched.

Still investigating the appropriate fix.

**Comment by smrq** [comment]
After doing some investigation, I decided to emit each file as it is added to the compiler host.  This should fix it.  Try latest.

**Comment by LPGhatguy** [comment]
This issue doesn't appear to be fixed as of the latest release, @smrq. I've been out of the office so I've been unable to test the nightlies.

**Comment by LPGhatguy** [comment]
I've fixed the gulpfile. I have a feeling that this might be the longstanding OS X FSEvents bug more than a tsify bug, because watching is broken in that reproduction repository entirely.
