### ISSUE TITLE
Dies on b._extensions.indexOf

### ISSUE THREAD

**Issue by moll** [smrq/tsify#64]
Hey,

Also dies on:
```
                if (b._extensions.indexOf('.ts') === -1)
                                 ^
TypeError: Cannot read property 'indexOf' of undefined
```

I take that's because it's using a private property and Browserify has since changed. ^_^

**Comment by moll** [comment]
Forgot to mention, that was with Browserify v11.0.1.

**Comment by moll** [comment]
I take that back. Sorry. I was implicitly assuming and using this as a transform, not as a plugin. Seems to work as a plugin.

**Comment by bcherny** [comment]
good find, thanks @moll!
