### ISSUE TITLE
Doesn't work with npm dependencies

### ISSUE THREAD

**Issue by nripendra** [smrq/tsify#66]
I have following line in code:
```js
import * as React from 'react';
```
Getting following error : **cannot find module 'react'.**

Here react is npm module installed in node_modules folder of project root.

This works fine with other gulp plugin like gulp-typescript..

I have set tsd.json and typings folder correctly.

What may be cause of problem?

**Comment by nripendra** [comment]
Ok when I put /// <reference path=".."/> pointing to react.d.ts file in typings folder (in one of my files) it is no more giving this particular error..

Now, I'm getting another error:
**ParseError: 'import' and 'export' may appear only with 'sourceType: module'**

I tried to solve issue by putting following config in browserify constructor (as suggested in some SO posts)
**extensions: ['.ts', '.tsx']**
but still doesn't work

**Comment by smrq** [comment]
Can you check whether you're running into the Browserify bug mentioned in #60?

**Comment by smrq** [comment]
Closing for now, please reopen if you still have an issue, ideally with a repro to work from
