### ISSUE TITLE
Set current working directory

### ISSUE THREAD

**Issue by aciccarello** [smrq/tsify#70]
I know you mentioned is a (comment)[https://github.com/smrq/tsify/issues/51#issuecomment-106096801] on #51  that tsify looks for tsconfig.json in the current working directory and up

Is there a way to set the current working directory? I'm running tsify from a gulpfile in the root of my project but I'd like to leave tsconfig.json with my source.

**Comment by smrq** [comment]
`gulp --cwd path/to/source`?

**Comment by aciccarello** [comment]
Okay, I was thinking tsify might have a config option to set the current working directory that it uses. But thinking about setting it in gulp seems to have pointed me in the [right direction](http://stackoverflow.com/a/28085111/4252741) using node's [process object](https://nodejs.org/api/process.html#process_process_chdir_directory) to change the current working directory.

**Comment by aciccarello** [comment]
It turns out that changing the current working directory didn't work well with my build tasks. I'll just pass in the compiler options as was suggested in [#51 (comment)](https://github.com/smrq/tsify/issues/51#issuecomment-105258892).
