### ISSUE TITLE
read from stdin

### ISSUE THREAD

**Issue by rosendi** [smrq/tsify#79]
I'am probably missing something obvious here, but is it possible to use the tsify when running browserify that reading from stdin? I ask because I'd like to try using tsify with browserify-rails, but it runs browserify via the command line and turns it reading from stdin. 

Example:

`echo "..." | browserifyinc -p [ tsify --module commonjs --target es5 --noImplicitAny --experimentalDecorators ] --list  -`

->

```
  return binding.lstat(pathModule._makeLong(path));
                                  ^
Error: ENOENT: no such file or directory, lstat '/Projects/angular2/app/assets/javascripts/_stream_0.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:844:18)
    at Object.realpathSync (fs.js:1438:21)
    at /Projects/angular2/node_modules/tsify/index.js:50:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush] (/Projects/angular2/node_modules/tsify/index.js:50:6)
    at DestroyableTransform.<anonymous> (/Projects/angular2/node_modules/tsify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:123:12)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
```

and debug info

```
[ { transform: [Function: bound ],
    options: { _flags: [Object] },
    global: undefined },
  { source: 'var t = require("./test");',
    entry: true,
    file: '/Projects/angular2/app/assets/javascripts/_stream_0.js',
    id: '/Projects/angular2/app/assets/javascripts/_stream_0.js',
    order: 0 },
  { transform: [Function: globalTr], global: true, options: {} } ]
```

**Comment by rosendi** [comment]
The problem was in `browserify-rails` gem.

**Comment by rigoleto** [comment]
I'm having this same issue, did you figure out a way around it?

**Comment by rosendi** [comment]
@rigoleto Take a look at browserify-rails/browserify-rails#110 and https://github.com/rosendi/browserify-rails and here is how to mix it together https://github.com/rosendi/figure-server/commit/9f85700c83a359c8ede00f1cf94c8247e7b4b569. I recommend you to switch from Sprockets to something like Gulp or Grunt since the compilation process is dramatically slow as well. If you develop Angular 2 application I also recommend you do not use Browser/Tsify bundle because in this case you have to use polyfills. The last point why I moved from Gulp/Browsery/Tsify to Gulp/Typescript/System.js (see `figure-server` master) was strange bugs with Angular and especially with Zone.js.

**Comment by rigoleto** [comment]
Thanks so much for your response. I'll have to figure out which option is best for us, might use Babel instead.

**Comment by rosendi** [comment]
You're welcome. To be more precise you have to use two polyfills https://github.com/ModuleLoader/es6-module-loader/blob/master/src/url-polyfill.js and es6-promise. System.js has already included them.
